apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:{{ k8s_ver_bare }}
    command:
    - /hyperkube
    - proxy
    - --config=/etc/kubernetes/proxy.conf
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/kubernetes/proxy-kubeconfig.yaml
      name: "kubeconfig"
      readOnly: true
    - mountPath: /etc/kubernetes/proxy.conf
      name: "config"
      readOnly: true
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  volumes:
  - name: lib-modules
    hostPath:
      path: /lib/modules
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - name: "kubeconfig"
    hostPath:
      path: "/etc/kubernetes/kubeconfig"
  - name: "config"
    hostPath:
      path: "/etc/kubernetes/proxy.conf"
