apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:{{ k8s_ver_bare }}
    command:
    - /hyperkube
    - proxy
    - --config=/etc/kubernetes/proxy.conf
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: /etc/kubernetes/proxy-kubeconfig.yaml
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes/ssl/ca.pem
        name: "etc-ca-cert"
        readOnly: true
      - mountPath: /etc/kubernetes/ssl/proxy.pem
        name: "etc-proxy-cert"
        readOnly: true
      - mountPath: /etc/kubernetes/ssl/proxy-key.pem
        name: "etc-proxy-key"
        readOnly: true
      - mountPath: /etc/kubernetes/proxy.conf
        name: "config"
        readOnly: true
      - mountPath: /lib/modules
        name: lib-modules
        readOnly: true
  volumes:
    - name: lib-modules
      hostPath:
        path: /lib/modules
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "/etc/kubernetes/proxy-kubeconfig.yaml"
    - name: "etc-ca-cert"
      hostPath:
        path: "/etc/kubernetes/ssl/ca.pem"
    - name: "etc-proxy-cert"
      hostPath:
        path: "/etc/kubernetes/ssl/proxy.pem"
    - name: "etc-proxy-key"
      hostPath:
        path: "/etc/kubernetes/ssl/proxy-key.pem"
    - name: "config"
      hostPath:
        path: "/etc/kubernetes/proxy.conf"
